# 服务器端口配置
server:
  port: 80

# 修改banner (springboot 图标)
spring:
  main:
    banner-mode: off

# 日志
# 1. 正常显示的信息
# logging.level.root = info

# 2. 报错信息
# logging.level.root = error

# 3. debug 信息
# logging.level.root = debug

# 自定义数据
book:
  - id: 1
    name: Qing1
  - id: 2
    name: Qing2

baseDir: C:\

userDir: ${baseDir}\Users

# 使用 "" 括起来的字符串能识别出转义字符 \t \n
# string: "spring\tboot\tlearning"

datasource:
  driver: mysql
  url: https
  username: 111
  password: 111