# 服务器端口配置
server:
  port: 80

# 修改banner (springboot 图标)
spring:
  main:
    banner-mode: off
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:330/springboot
      username: root
      password: 2514632453

# 数据库主键生成策略：自增（默认是自动分配主键）
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # 开启运行日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 数据库表名前缀
#      table-prefix: tbl_


# 日志
# 1. 正常显示的信息
# logging.level.root = info

# 2. 报错信息
# logging.level.root = error

# 3. debug 信息
# logging.level.root = debug

# 自定义数据
book:
  - id: 1
    name: Qing1
  - id: 2
    name: Qing2

baseDir: C:\

userDir: ${baseDir}\Users

# 使用 "" 括起来的字符串能识别出转义字符 \t \n
# string: "spring\tboot\tlearning"

source:
  driver: mysql
  url: https
  username: 111
  password: 111